const STORAGE_KEY = 'farsi-daily-v1';
const DAY_MS = 86400000;
let reviewQueue = [];
let reviewIndex = 0;
let currentFilter = 'all';
let deferredInstallPrompt = null;
let activeAudio = null;
let activeUtterance = null;
let speechRequest = 0;
let voiceCache = [];
const $ = (id) => document.getElementById(id);
const todayKey = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
const now = () => Date.now();
function defaultState(){return{cards:{},history:{},totalGood:0,totalBad:0,lastOpen:null}}
function loadState(){try{return{...defaultState(),...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return defaultState()}}
let state=loadState();
function saveState(){state.lastOpen=todayKey();localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function dayNumber(){const s=typeof CURRICULUM_START!=='undefined'?CURRICULUM_START:'2024-01-01';const[y,m,d]=s.split('-').map(Number);const start=Date.UTC(y,m-1,d),n=new Date();return Math.max(0,Math.floor((Date.UTC(n.getFullYear(),n.getMonth(),n.getDate())-start)/DAY_MS))}
function todaysWordIndex(){const order=typeof DAILY_ORDER!=='undefined'&&DAILY_ORDER.length?DAILY_ORDER:WORDS.map((_,i)=>i);return order[((dayNumber()%order.length)+order.length)%order.length]}
function getWord(index){return WORDS[index]}
function escapeHTML(value){return String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function renderVerbDetails(containerId,word){const c=$(containerId);if(!c)return;const key=word?.verbKey||(word?.pos==='verb'?word.fa:null);const v=key&&typeof getVerbConjugations==='function'?getVerbConjugations(key):null;c.classList.toggle('hidden',!v);if(!v){c.innerHTML='';return}const labels={present:'Present',past:'Past',subjunctive:'Subjunctive',future:'Future'},help={present:'I go / I am going',past:'I went',subjunctive:'that I go / let me go',future:'I will go'};const tables=Object.entries(labels).map(([tense],ti)=>`<section class="conjugation-tense${ti===0?' active':''}" data-tense-panel="${tense}"><p class="tense-help">${help[tense]}</p>${v[tense].map((form,i)=>`<div class="conjugation-row"><span class="conjugation-pronoun" lang="fa" dir="rtl">${escapeHTML(v.pronouns[i])}</span><strong lang="fa" dir="rtl">${escapeHTML(form)}</strong><button type="button" class="conjugation-speak" data-speak-form="${escapeHTML(form)}" aria-label="Speak ${escapeHTML(form)}">🔊</button></div>`).join('')}</section>`).join('');c.innerHTML=`<div class="verb-heading"><div><span class="verb-label">VERB CONJUGATIONS</span><strong>${escapeHTML(v.infinitive)} · ${escapeHTML(v.en)}</strong></div><span class="verb-infinitive">${escapeHTML(v.latin)}</span></div><div class="tense-tabs" role="tablist" aria-label="Verb tense">${Object.entries(labels).map(([tense,label],i)=>`<button type="button" data-tense="${tense}" class="${i===0?'active':''}">${label}</button>`).join('')}</div><div class="conjugation-tables">${tables}</div>`}
function bindVerbPanel(id){const c=$(id);if(!c||c.dataset.bound==='true')return;c.dataset.bound='true';c.addEventListener('click',e=>{const t=e.target.closest('[data-tense]');if(t){const tense=t.dataset.tense;c.querySelectorAll('[data-tense]').forEach(b=>b.classList.toggle('active',b===t));c.querySelectorAll('[data-tense-panel]').forEach(p=>p.classList.toggle('active',p.dataset.tensePanel===tense));return}const b=e.target.closest('[data-speak-form]');if(b)speak(b.dataset.speakForm,b)})}
function addWord(index,silent=false){if(state.cards[index])return false;state.cards[index]={addedAt:now(),dueAt:now(),intervalDays:0,streak:0,good:0,bad:0,lastResult:null,lastReviewedAt:null};saveState();if(!silent)toast('Added to your flashcards');renderAll();return true}
function ensureTodayLogged(){const key=todayKey();if(!state.history[key])state.history[key]={opened:true,reviewed:0};else state.history[key].opened=true;saveState()}
function formatDate(ts){return new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric'}).format(new Date(ts))}
function refreshVoices(){if(!('speechSynthesis'in window))return[];voiceCache=window.speechSynthesis.getVoices()||[];return voiceCache}
function findPersianVoice(){const voices=refreshVoices();return voices.find(v=>/^fa(?:-|_|$)/i.test(v.lang))||voices.find(v=>/persian|farsi|iran/i.test(`${v.name} ${v.lang}`))}
function stopSpeech(){speechRequest+=1;if(activeAudio){activeAudio.pause();activeAudio.removeAttribute('src');activeAudio.load();activeAudio=null}if('speechSynthesis'in window)window.speechSynthesis.cancel();activeUtterance=null}
function setSpeechButtonBusy(button,busy){if(!button)return;button.disabled=busy;button.setAttribute('aria-busy',String(busy))}
function speakWithBrowserVoice(text,requestId,button){if(!('speechSynthesis'in window)||requestId!==speechRequest){setSpeechButtonBusy(button,false);toast('Audio could not play in this browser');return}const s=window.speechSynthesis,u=new SpeechSynthesisUtterance(text),voice=findPersianVoice();let started=false;if(voice)u.voice=voice;u.lang=voice?.lang||'fa-IR';u.rate=.78;u.pitch=1;u.volume=1;u.onstart=()=>{if(requestId!==speechRequest)return;started=true;setSpeechButtonBusy(button,false)};u.onend=()=>{if(requestId!==speechRequest)return;setSpeechButtonBusy(button,false);activeUtterance=null};u.onerror=()=>{if(requestId!==speechRequest)return;setSpeechButtonBusy(button,false);activeUtterance=null;toast('No Persian voice is available. Check your sound and internet connection.')};activeUtterance=u;s.cancel();setTimeout(()=>{if(requestId!==speechRequest)return;s.resume();s.speak(u)},70);setTimeout(()=>{if(requestId!==speechRequest||started)return;s.cancel();setSpeechButtonBusy(button,false);toast('No Persian voice is installed. The online pronunciation also failed.')},3500)}
function speak(text,button=null){stopSpeech();const requestId=speechRequest;setSpeechButtonBusy(button,true);const encoded=encodeURIComponent(text),audio=document.createElement('audio');audio.preload='auto';audio.playsInline=true;[`https://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&tl=fa&ttsspeed=0.8&q=${encoded}`,`https://translate.googleapis.com/translate_tts?ie=UTF-8&client=gtx&tl=fa&ttsspeed=0.8&q=${encoded}`].forEach(url=>{const source=document.createElement('source');source.src=url;source.type='audio/mpeg';audio.appendChild(source)});activeAudio=audio;let fallbackStarted=false,didStart=false;const fallback=()=>{if(fallbackStarted||requestId!==speechRequest)return;fallbackStarted=true;if(activeAudio===audio)activeAudio=null;audio.pause();speakWithBrowserVoice(text,requestId,button)};audio.addEventListener('playing',()=>{if(requestId!==speechRequest)return;didStart=true;setSpeechButtonBusy(button,false)},{once:true});audio.addEventListener('ended',()=>{if(requestId!==speechRequest)return;setSpeechButtonBusy(button,false);if(activeAudio===audio)activeAudio=null},{once:true});audio.addEventListener('error',fallback,{once:true});const p=audio.play();if(p&&typeof p.catch==='function')p.catch(fallback);setTimeout(()=>{if(!didStart)fallback()},5000)}
