function renderToday(){const index=todaysWordIndex(),word=getWord(index);$('todayFarsi').textContent=word.fa;$('todayLatin').textContent=word.latin;$('todayMeaning').textContent=word.en;$('wordCategory').textContent=word.pos==='verb'?'Verb':word.category;const dateText=new Intl.DateTimeFormat(undefined,{weekday:'long',month:'long',day:'numeric'}).format(new Date());$('wordDay').textContent=`Frequency #${word.rank||index+1} of ${typeof DAILY_ORDER!=='undefined'?DAILY_ORDER.length:WORDS.length} · ${dateText}`;const box=$('todayExampleFa').closest('.example-box'),has=Boolean(word.exFa||word.exLatin||word.exEn);box.classList.toggle('hidden',!has);$('todayExampleFa').textContent=word.exFa||'';$('todayExampleLatin').textContent=word.exLatin||'';$('todayExampleEn').textContent=word.exEn||'';renderVerbDetails('todayVerbPanel',word);const added=Boolean(state.cards[index]);$('addTodayBtn').disabled=added;$('addTodayBtn').textContent=added?'Added to my words':'Add to my words'}
function dueCardIndexes(){return Object.keys(state.cards).map(Number).filter(i=>state.cards[i].dueAt<=now()).sort((a,b)=>state.cards[a].dueAt-state.cards[b].dueAt)}
function statusFor(card){if(card.bad>card.good||card.lastResult==='bad')return'missed';if(card.streak>=4||card.intervalDays>=14)return'strong';return'learning'}
function streakDays(){let count=0,cursor=new Date();cursor.setHours(0,0,0,0);for(let i=0;i<3650;i++){const key=cursor.toISOString().slice(0,10);if(state.history[key])count++;else if(i!==0)break;cursor=new Date(cursor.getTime()-DAY_MS)}return count}
function renderStats(){const learned=Object.keys(state.cards).length,due=dueCardIndexes().length,attempts=state.totalGood+state.totalBad;$('streakStat').textContent=streakDays();$('learnedStat').textContent=learned;$('dueStat').textContent=due;$('accuracyStat').textContent=attempts?`${Math.round(state.totalGood/attempts*100)}%`:'—';$('reviewBadge').textContent=due}
function renderDeck(){const list=$('deckList'),query=$('searchInput').value.trim().toLowerCase(),entries=Object.keys(state.cards).map(Number).filter(i=>{const w=getWord(i),c=state.cards[i];return(!query||`${w.fa} ${w.latin} ${w.en}`.toLowerCase().includes(query))&&(currentFilter==='all'||statusFor(c)===currentFilter)}).sort((a,b)=>state.cards[b].addedAt-state.cards[a].addedAt);list.innerHTML='';$('deckEmpty').classList.toggle('hidden',entries.length>0||Object.keys(state.cards).length>0);entries.forEach(i=>{const w=getWord(i),c=state.cards[i],status=statusFor(c),due=c.dueAt<=now()?'Due now':`Next ${formatDate(c.dueAt)}`,item=document.createElement('article');item.className='deck-item';item.innerHTML=`<div class="deck-fa" lang="fa" dir="rtl">${escapeHTML(w.fa)}</div><div class="deck-main"><strong>${escapeHTML(w.latin)} · ${escapeHTML(w.en)}</strong><span><i class="status-dot ${status}"></i>#${w.rank||i+1} · ${w.pos==='verb'?'Verb · ':''}${status==='missed'?'Needs work':status[0].toUpperCase()+status.slice(1)} · ${due} · ${c.good} right / ${c.bad} missed</span></div><div class="deck-actions"><button type="button" data-speak="${i}" aria-label="Speak ${escapeHTML(w.fa)}">🔊</button><button type="button" data-review="${i}" aria-label="Review ${escapeHTML(w.fa)}">↻</button><button type="button" data-remove="${i}" aria-label="Remove ${escapeHTML(w.fa)}">×</button></div>`;list.appendChild(item)})}
function buildReviewQueue(forceAny=false,singleIndex=null){if(singleIndex!==null)reviewQueue=[singleIndex];else{reviewQueue=dueCardIndexes();if(!reviewQueue.length&&forceAny)reviewQueue=Object.keys(state.cards).map(Number).sort(()=>Math.random()-.5)}reviewIndex=0;renderReviewCard()}
function renderReviewCard(){const has=reviewQueue.length>0&&reviewIndex<reviewQueue.length;$('reviewEmpty').classList.toggle('hidden',has);$('reviewCard').classList.toggle('hidden',!has);if(!has)return;const index=reviewQueue[reviewIndex],word=getWord(index);$('reviewPrompt').textContent=word.fa;$('reviewLatin').textContent=word.latin;$('reviewMeaning').textContent=word.en;renderVerbDetails('reviewVerbPanel',word);$('reviewCounter').textContent=`${reviewIndex+1} of ${reviewQueue.length}`;$('reviewProgressFill').style.width=`${reviewIndex/reviewQueue.length*100}%`;$('reviewAnswer').classList.add('hidden');$('revealBtn').classList.remove('hidden')}
function rateCard(result){const index=reviewQueue[reviewIndex],card=state.cards[index],key=todayKey();card.lastReviewedAt=now();card.lastResult=result;if(result==='bad'){card.bad+=1;card.streak=0;card.intervalDays=0;card.dueAt=now()+600000;state.totalBad+=1;reviewQueue.push(index)}else{card.good+=1;card.streak+=1;const steps=[1,3,7,14,30,60,120];card.intervalDays=steps[Math.min(card.streak-1,steps.length-1)];card.dueAt=now()+card.intervalDays*DAY_MS;state.totalGood+=1}state.history[key]=state.history[key]||{opened:true,reviewed:0};state.history[key].reviewed+=1;saveState();reviewIndex+=1;renderAll();renderReviewCard()}
function showView(name){document.querySelectorAll('.view').forEach(el=>el.classList.toggle('active',el.id===`${name}View`));document.querySelectorAll('.tab').forEach(el=>el.classList.toggle('active',el.dataset.view===name));if(name==='review')buildReviewQueue(false);if(name==='deck')renderDeck()}
function renderAll(){renderToday();renderStats();renderDeck()}
let toastTimer;function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
