const SCRIPT_LESSONS = [
  {letter:'ا',name:'alef',nameFa:'الف',sound:'a / â',forms:['ا','ا','ـا','ـا'],exampleFa:'آب',exampleLatin:'âb',exampleEn:'water'},
  {letter:'ب',name:'be',nameFa:'بِ',sound:'b',forms:['ب','بـ','ـبـ','ـب'],exampleFa:'بابا',exampleLatin:'bâbâ',exampleEn:'dad'},
  {letter:'پ',name:'pe',nameFa:'پِ',sound:'p',forms:['پ','پـ','ـپـ','ـپ'],exampleFa:'پول',exampleLatin:'pul',exampleEn:'money'},
  {letter:'ت',name:'te',nameFa:'تِ',sound:'t',forms:['ت','تـ','ـتـ','ـت'],exampleFa:'تو',exampleLatin:'to',exampleEn:'you'},
  {letter:'ث',name:'se',nameFa:'ثِ',sound:'s (mostly Arabic loanwords)',forms:['ث','ثـ','ـثـ','ـث'],exampleFa:'ثانیه',exampleLatin:'sâniye',exampleEn:'second'},
  {letter:'ج',name:'jim',nameFa:'جیم',sound:'j',forms:['ج','جـ','ـجـ','ـج'],exampleFa:'جای',exampleLatin:'jâ',exampleEn:'place'},
  {letter:'چ',name:'che',nameFa:'چِ',sound:'ch',forms:['چ','چـ','ـچـ','ـچ'],exampleFa:'چای',exampleLatin:'châi',exampleEn:'tea'},
  {letter:'ح',name:'he-ye jimi',nameFa:'حِ',sound:'h',forms:['ح','حـ','ـحـ','ـح'],exampleFa:'حال',exampleLatin:'hâl',exampleEn:'condition / mood'},
  {letter:'خ',name:'khe',nameFa:'خِ',sound:'kh',forms:['خ','خـ','ـخـ','ـخ'],exampleFa:'خانه',exampleLatin:'khâne',exampleEn:'home'},
  {letter:'د',name:'dâl',nameFa:'دال',sound:'d',forms:['د','د','ـد','ـد'],exampleFa:'در',exampleLatin:'dar',exampleEn:'door / in'},
  {letter:'ذ',name:'zâl',nameFa:'ذال',sound:'z (mostly Arabic loanwords)',forms:['ذ','ذ','ـذ','ـذ'],exampleFa:'لذت',exampleLatin:'lezzat',exampleEn:'enjoyment'},
  {letter:'ر',name:'re',nameFa:'رِ',sound:'r',forms:['ر','ر','ـر','ـر'],exampleFa:'راه',exampleLatin:'râh',exampleEn:'way / road'},
  {letter:'ز',name:'ze',nameFa:'زِ',sound:'z',forms:['ز','ز','ـز','ـز'],exampleFa:'زن',exampleLatin:'zan',exampleEn:'woman'},
  {letter:'ژ',name:'zhe',nameFa:'ژِ',sound:'zh, like “s” in vision',forms:['ژ','ژ','ـژ','ـژ'],exampleFa:'ژاله',exampleLatin:'zhâle',exampleEn:'dew'},
  {letter:'س',name:'sin',nameFa:'سین',sound:'s',forms:['س','سـ','ـسـ','ـس'],exampleFa:'سلام',exampleLatin:'salâm',exampleEn:'hello'},
  {letter:'ش',name:'shin',nameFa:'شین',sound:'sh',forms:['ش','شـ','ـشـ','ـش'],exampleFa:'شب',exampleLatin:'shab',exampleEn:'night'},
  {letter:'ص',name:'sâd',nameFa:'صاد',sound:'s',forms:['ص','صـ','ـصـ','ـص'],exampleFa:'صبح',exampleLatin:'sobh',exampleEn:'morning'},
  {letter:'ض',name:'zâd',nameFa:'ضاد',sound:'z',forms:['ض','ضـ','ـضـ','ـض'],exampleFa:'ضروری',exampleLatin:'zaruri',exampleEn:'necessary'},
  {letter:'ط',name:'tâ',nameFa:'طا',sound:'t',forms:['ط','طـ','ـطـ','ـط'],exampleFa:'طبیعت',exampleLatin:'tabiat',exampleEn:'nature'},
  {letter:'ظ',name:'zâ',nameFa:'ظا',sound:'z',forms:['ظ','ظـ','ـظـ','ـظ'],exampleFa:'ظهر',exampleLatin:'zohr',exampleEn:'noon'},
  {letter:'ع',name:'eyn',nameFa:'عین',sound:'throat sound / vowel carrier',forms:['ع','عـ','ـعـ','ـع'],exampleFa:'عالی',exampleLatin:'âli',exampleEn:'great'},
  {letter:'غ',name:'gheyn',nameFa:'غین',sound:'gh',forms:['غ','غـ','ـغـ','ـغ'],exampleFa:'غذا',exampleLatin:'ghazâ',exampleEn:'food'},
  {letter:'ف',name:'fe',nameFa:'فِ',sound:'f',forms:['ف','فـ','ـفـ','ـف'],exampleFa:'فردا',exampleLatin:'fardâ',exampleEn:'tomorrow'},
  {letter:'ق',name:'ghâf',nameFa:'قاف',sound:'gh / q',forms:['ق','قـ','ـقـ','ـق'],exampleFa:'قهوه',exampleLatin:'ghahve',exampleEn:'coffee'},
  {letter:'ک',name:'kâf',nameFa:'کاف',sound:'k',forms:['ک','کـ','ـکـ','ـک'],exampleFa:'کتاب',exampleLatin:'ketâb',exampleEn:'book'},
  {letter:'گ',name:'gâf',nameFa:'گاف',sound:'g',forms:['گ','گـ','ـگـ','ـگ'],exampleFa:'گربه',exampleLatin:'gorbe',exampleEn:'cat'},
  {letter:'ل',name:'lâm',nameFa:'لام',sound:'l',forms:['ل','لـ','ـلـ','ـل'],exampleFa:'لطفاً',exampleLatin:'lotfan',exampleEn:'please'},
  {letter:'م',name:'mim',nameFa:'میم',sound:'m',forms:['م','مـ','ـمـ','ـم'],exampleFa:'من',exampleLatin:'man',exampleEn:'I / me'},
  {letter:'ن',name:'nun',nameFa:'نون',sound:'n',forms:['ن','نـ','ـنـ','ـن'],exampleFa:'نان',exampleLatin:'nân',exampleEn:'bread'},
  {letter:'و',name:'vâv',nameFa:'واو',sound:'v / o / u',forms:['و','و','ـو','ـو'],exampleFa:'وقت',exampleLatin:'vaght',exampleEn:'time'},
  {letter:'ه',name:'he',nameFa:'هِ',sound:'h / e at the end of words',forms:['ه','هـ','ـهـ','ـه'],exampleFa:'هوا',exampleLatin:'havâ',exampleEn:'weather / air'},
  {letter:'ی',name:'ye',nameFa:'یِ',sound:'y / i',forms:['ی','یـ','ـیـ','ـی'],exampleFa:'یک',exampleLatin:'yek',exampleEn:'one'}
];
