const WORDS = [
  {fa:'سلام', latin:'salâm', en:'hello', category:'Everyday', exFa:'سلام، حالت چطوره؟', exLatin:'Salâm, hâlet chetore?', exEn:'Hello, how are you?'},
  {fa:'ممنون', latin:'mamnun', en:'thank you', category:'Everyday', exFa:'خیلی ممنون.', exLatin:'Kheyli mamnun.', exEn:'Thank you very much.'},
  {fa:'لطفاً', latin:'lotfan', en:'please', category:'Everyday', exFa:'یک چای، لطفاً.', exLatin:'Yek chây, lotfan.', exEn:'One tea, please.'},
  {fa:'بله', latin:'bale', en:'yes', category:'Basics', exFa:'بله، آماده‌ام.', exLatin:'Bale, âmâde-am.', exEn:'Yes, I am ready.'},
  {fa:'نه', latin:'na', en:'no', category:'Basics', exFa:'نه، نمی‌دانم.', exLatin:'Na, nemidânam.', exEn:'No, I do not know.'},
  {fa:'خداحافظ', latin:'khodâhâfez', en:'goodbye', category:'Everyday', exFa:'خداحافظ، فردا می‌بینمت.', exLatin:'Khodâhâfez, fardâ mibinamet.', exEn:'Goodbye, I will see you tomorrow.'},
  {fa:'خوب', latin:'khub', en:'good', category:'Adjective', exFa:'امروز روز خوبی است.', exLatin:'Emruz ruz-e khubi ast.', exEn:'Today is a good day.'},
  {fa:'بد', latin:'bad', en:'bad', category:'Adjective', exFa:'هوا خیلی بد نیست.', exLatin:'Havâ kheyli bad nist.', exEn:'The weather is not very bad.'},
  {fa:'آب', latin:'âb', en:'water', category:'Food', exFa:'آب سرد می‌خواهم.', exLatin:'Âb-e sard mikhâham.', exEn:'I want cold water.'},
  {fa:'غذا', latin:'ghazâ', en:'food', category:'Food', exFa:'این غذا خوشمزه است.', exLatin:'In ghazâ khoshmaze ast.', exEn:'This food is delicious.'},
  {fa:'چای', latin:'chây', en:'tea', category:'Food', exFa:'من چای دوست دارم.', exLatin:'Man chây dust dâram.', exEn:'I like tea.'},
  {fa:'قهوه', latin:'ghahve', en:'coffee', category:'Food', exFa:'صبح قهوه می‌خورم.', exLatin:'Sobh ghahve mikhoram.', exEn:'I drink coffee in the morning.'},
  {fa:'خانه', latin:'khâne', en:'home / house', category:'Places', exFa:'من در خانه هستم.', exLatin:'Man dar khâne hastam.', exEn:'I am at home.'},
  {fa:'مدرسه', latin:'madrese', en:'school', category:'Places', exFa:'او به مدرسه می‌رود.', exLatin:'U be madrese miravad.', exEn:'She goes to school.'},
  {fa:'کار', latin:'kâr', en:'work', category:'Everyday', exFa:'امروز کار دارم.', exLatin:'Emruz kâr dâram.', exEn:'I have work today.'},
  {fa:'دوست', latin:'dust', en:'friend', category:'People', exFa:'او دوست من است.', exLatin:'U dust-e man ast.', exEn:'He is my friend.'},
  {fa:'خانواده', latin:'khânevâde', en:'family', category:'People', exFa:'خانواده‌ام را دوست دارم.', exLatin:'Khânevâde-am râ dust dâram.', exEn:'I love my family.'},
  {fa:'مادر', latin:'mâdar', en:'mother', category:'People', exFa:'مادرم مهربان است.', exLatin:'Mâdaram mehrabân ast.', exEn:'My mother is kind.'},
  {fa:'پدر', latin:'pedar', en:'father', category:'People', exFa:'پدرم در خانه است.', exLatin:'Pedaram dar khâne ast.', exEn:'My father is at home.'},
  {fa:'بچه', latin:'bache', en:'child', category:'People', exFa:'آن بچه خوشحال است.', exLatin:'Ân bache khoshhâl ast.', exEn:'That child is happy.'},
  {fa:'امروز', latin:'emruz', en:'today', category:'Time', exFa:'امروز هوا گرم است.', exLatin:'Emruz havâ garm ast.', exEn:'The weather is warm today.'},
  {fa:'فردا', latin:'fardâ', en:'tomorrow', category:'Time', exFa:'فردا می‌بینمت.', exLatin:'Fardâ mibinamet.', exEn:'I will see you tomorrow.'},
  {fa:'دیروز', latin:'diruz', en:'yesterday', category:'Time', exFa:'دیروز باران آمد.', exLatin:'Diruz bârân âmad.', exEn:'It rained yesterday.'},
  {fa:'صبح', latin:'sobh', en:'morning', category:'Time', exFa:'صبح بخیر!', exLatin:'Sobh bekheyr!', exEn:'Good morning!'},
  {fa:'شب', latin:'shab', en:'night', category:'Time', exFa:'شب بخیر.', exLatin:'Shab bekheyr.', exEn:'Good night.'},
  {fa:'الان', latin:'alân', en:'now', category:'Time', exFa:'الان وقت دارم.', exLatin:'Alân vaght dâram.', exEn:'I have time now.'},
  {fa:'اینجا', latin:'injâ', en:'here', category:'Places', exFa:'من اینجا هستم.', exLatin:'Man injâ hastam.', exEn:'I am here.'},
  {fa:'آنجا', latin:'ânjâ', en:'there', category:'Places', exFa:'ماشین آنجاست.', exLatin:'Mâshin ânjâst.', exEn:'The car is there.'},
  {fa:'کجا', latin:'kojâ', en:'where', category:'Question', exFa:'دستشویی کجاست؟', exLatin:'Dastshuyi kojâst?', exEn:'Where is the restroom?'},
  {fa:'چی', latin:'chi', en:'what', category:'Question', exFa:'این چیه؟', exLatin:'In chie?', exEn:'What is this?'},
  {fa:'چرا', latin:'cherâ', en:'why', category:'Question', exFa:'چرا ناراحتی؟', exLatin:'Cherâ nârâhati?', exEn:'Why are you upset?'},
  {fa:'چطور', latin:'chetor', en:'how', category:'Question', exFa:'چطور هستی؟', exLatin:'Chetor hasti?', exEn:'How are you?'},
  {fa:'کی', latin:'key', en:'when', category:'Question', exFa:'کی می‌آیی؟', exLatin:'Key miâyi?', exEn:'When are you coming?'},
  {fa:'من', latin:'man', en:'I / me', category:'Basics', exFa:'من فارسی یاد می‌گیرم.', exLatin:'Man fârsi yâd migiram.', exEn:'I am learning Persian.'},
  {fa:'تو', latin:'to', en:'you (informal)', category:'Basics', exFa:'تو آماده‌ای؟', exLatin:'To âmâde-i?', exEn:'Are you ready?'},
  {fa:'شما', latin:'shomâ', en:'you (polite/plural)', category:'Basics', exFa:'شما کجا هستید؟', exLatin:'Shomâ kojâ hastid?', exEn:'Where are you?'},
  {fa:'او', latin:'u', en:'he / she', category:'Basics', exFa:'او فارسی صحبت می‌کند.', exLatin:'U fârsi sohbat mikonad.', exEn:'He or she speaks Persian.'},
  {fa:'ما', latin:'mâ', en:'we', category:'Basics', exFa:'ما آماده‌ایم.', exLatin:'Mâ âmâde-im.', exEn:'We are ready.'},
  {fa:'دوست داشتن', latin:'dust dâshtan', en:'to like / love', category:'Verb', exFa:'من موسیقی دوست دارم.', exLatin:'Man musighi dust dâram.', exEn:'I like music.'},
  {fa:'خواستن', latin:'khâstan', en:'to want', category:'Verb', exFa:'من آب می‌خواهم.', exLatin:'Man âb mikhâham.', exEn:'I want water.'},
  {fa:'رفتن', latin:'raftan', en:'to go', category:'Verb', exFa:'می‌خواهم بروم.', exLatin:'Mikhâham beravam.', exEn:'I want to go.'},
  {fa:'آمدن', latin:'âmadan', en:'to come', category:'Verb', exFa:'فردا می‌آیم.', exLatin:'Fardâ miâyam.', exEn:'I will come tomorrow.'},
  {fa:'دیدن', latin:'didan', en:'to see', category:'Verb', exFa:'خوشحالم که می‌بینمت.', exLatin:'Khoshhâlam ke mibinamet.', exEn:'I am happy to see you.'},
  {fa:'خوردن', latin:'khordan', en:'to eat', category:'Verb', exFa:'می‌خواهم غذا بخورم.', exLatin:'Mikhâham ghazâ bokhoram.', exEn:'I want to eat food.'},
  {fa:'نوشیدن', latin:'nushidan', en:'to drink', category:'Verb', exFa:'آب بنوش.', exLatin:'Âb benush.', exEn:'Drink water.'},
  {fa:'گفتن', latin:'goftan', en:'to say', category:'Verb', exFa:'چی گفتی؟', exLatin:'Chi gofti?', exEn:'What did you say?'},
  {fa:'دانستن', latin:'dânestan', en:'to know', category:'Verb', exFa:'نمی‌دانم.', exLatin:'Nemidânam.', exEn:'I do not know.'},
  {fa:'فهمیدن', latin:'fahmidan', en:'to understand', category:'Verb', exFa:'می‌فهمم.', exLatin:'Mifahmam.', exEn:'I understand.'},
  {fa:'کمک', latin:'komak', en:'help', category:'Everyday', exFa:'کمک می‌خواهید؟', exLatin:'Komak mikhâhid?', exEn:'Do you need help?'},
  {fa:'پول', latin:'pul', en:'money', category:'Everyday', exFa:'پول نقد ندارم.', exLatin:'Pul-e naghd nadâram.', exEn:'I do not have cash.'},
  {fa:'ماشین', latin:'mâshin', en:'car', category:'Travel', exFa:'ماشین من سفید است.', exLatin:'Mâshin-e man sefid ast.', exEn:'My car is white.'},
  {fa:'خیابان', latin:'khiyâbân', en:'street', category:'Travel', exFa:'این خیابان شلوغ است.', exLatin:'In khiyâbân sholugh ast.', exEn:'This street is busy.'},
  {fa:'هواپیما', latin:'havâpeymâ', en:'airplane', category:'Travel', exFa:'هواپیما آماده است.', exLatin:'Havâpeymâ âmâde ast.', exEn:'The airplane is ready.'},
  {fa:'سفر', latin:'safar', en:'trip / travel', category:'Travel', exFa:'سفر خوبی داشته باشی.', exLatin:'Safar-e khubi dâshte bâshi.', exEn:'Have a good trip.'},
  {fa:'گرم', latin:'garm', en:'warm / hot', category:'Adjective', exFa:'چای گرم است.', exLatin:'Chây garm ast.', exEn:'The tea is hot.'},
  {fa:'سرد', latin:'sard', en:'cold', category:'Adjective', exFa:'آب خیلی سرد است.', exLatin:'Âb kheyli sard ast.', exEn:'The water is very cold.'},
  {fa:'بزرگ', latin:'bozorg', en:'big', category:'Adjective', exFa:'خانه بزرگ است.', exLatin:'Khâne bozorg ast.', exEn:'The house is big.'},
  {fa:'کوچک', latin:'kuchak', en:'small', category:'Adjective', exFa:'یک قهوه کوچک می‌خواهم.', exLatin:'Yek ghahve-ye kuchak mikhâham.', exEn:'I want a small coffee.'},
  {fa:'زیبا', latin:'zibâ', en:'beautiful', category:'Adjective', exFa:'این شهر زیباست.', exLatin:'In shahr zibâst.', exEn:'This city is beautiful.'},
  {fa:'خوشحال', latin:'khoshhâl', en:'happy', category:'Feeling', exFa:'من خیلی خوشحالم.', exLatin:'Man kheyli khoshhâlam.', exEn:'I am very happy.'},
  {fa:'خسته', latin:'khaste', en:'tired', category:'Feeling', exFa:'امروز خسته‌ام.', exLatin:'Emruz khaste-am.', exEn:'I am tired today.'},
  {fa:'گرسنه', latin:'gorosne', en:'hungry', category:'Feeling', exFa:'من گرسنه‌ام.', exLatin:'Man gorosne-am.', exEn:'I am hungry.'},
  {fa:'تشنه', latin:'teshne', en:'thirsty', category:'Feeling', exFa:'خیلی تشنه‌ام.', exLatin:'Kheyli teshne-am.', exEn:'I am very thirsty.'},
  {fa:'دوستت دارم', latin:'duset dâram', en:'I love you', category:'Useful phrase', exFa:'من دوستت دارم.', exLatin:'Man duset dâram.', exEn:'I love you.'},
  {fa:'حالت چطوره؟', latin:'hâlet chetore?', en:'how are you?', category:'Useful phrase', exFa:'سلام، حالت چطوره؟', exLatin:'Salâm, hâlet chetore?', exEn:'Hello, how are you?'},
  {fa:'خوش آمدید', latin:'khosh âmadid', en:'welcome', category:'Useful phrase', exFa:'به خانه ما خوش آمدید.', exLatin:'Be khâne-ye mâ khosh âmadid.', exEn:'Welcome to our home.'},
  {fa:'ببخشید', latin:'bebakhshid', en:'excuse me / sorry', category:'Useful phrase', exFa:'ببخشید، ساعت چنده؟', exLatin:'Bebakhshid, sâat chande?', exEn:'Excuse me, what time is it?'},
  {fa:'اشکالی ندارد', latin:'eshkâli nadârad', en:'no problem', category:'Useful phrase', exFa:'اشکالی ندارد، نگران نباش.', exLatin:'Eshkâli nadârad, negarân nabâsh.', exEn:'No problem, do not worry.'},
  {fa:'آماده', latin:'âmâde', en:'ready', category:'Adjective', exFa:'من آماده‌ام.', exLatin:'Man âmâde-am.', exEn:'I am ready.'},
  {fa:'صبر کن', latin:'sabr kon', en:'wait', category:'Useful phrase', exFa:'یک دقیقه صبر کن.', exLatin:'Yek daghighe sabr kon.', exEn:'Wait one minute.'},
  {fa:'بیا', latin:'biyâ', en:'come', category:'Useful phrase', exFa:'بیا اینجا.', exLatin:'Biyâ injâ.', exEn:'Come here.'},
  {fa:'برو', latin:'boro', en:'go', category:'Useful phrase', exFa:'برو خانه.', exLatin:'Boro khâne.', exEn:'Go home.'},
  {fa:'آرام', latin:'ârâm', en:'calm / quiet', category:'Adjective', exFa:'آرام باش.', exLatin:'Ârâm bâsh.', exEn:'Stay calm.'},
  {fa:'سریع', latin:'sari', en:'fast / quickly', category:'Adjective', exFa:'لطفاً سریع بیا.', exLatin:'Lotfan sari biyâ.', exEn:'Please come quickly.'},
  {fa:'آهسته', latin:'âheste', en:'slowly', category:'Adjective', exFa:'آهسته صحبت کن.', exLatin:'Âheste sohbat kon.', exEn:'Speak slowly.'},
  {fa:'راست', latin:'râst', en:'right / correct', category:'Direction', exFa:'به راست بپیچ.', exLatin:'Be râst bepich.', exEn:'Turn right.'},
  {fa:'چپ', latin:'chap', en:'left', category:'Direction', exFa:'به چپ برو.', exLatin:'Be chap boro.', exEn:'Go left.'},
  {fa:'مستقیم', latin:'mostaghim', en:'straight', category:'Direction', exFa:'مستقیم برو.', exLatin:'Mostaghim boro.', exEn:'Go straight.'},
  {fa:'بالا', latin:'bâlâ', en:'up / above', category:'Direction', exFa:'به بالا نگاه کن.', exLatin:'Be bâlâ negâh kon.', exEn:'Look up.'},
  {fa:'پایین', latin:'pâyin', en:'down / below', category:'Direction', exFa:'پایین بیا.', exLatin:'Pâyin biyâ.', exEn:'Come down.'},
  {fa:'نزدیک', latin:'nazdik', en:'near', category:'Places', exFa:'فروشگاه نزدیک است.', exLatin:'Forushgâh nazdik ast.', exEn:'The store is near.'},
  {fa:'دور', latin:'dur', en:'far', category:'Places', exFa:'فرودگاه دور است.', exLatin:'Forudgâh dur ast.', exEn:'The airport is far.'},
  {fa:'باز', latin:'bâz', en:'open', category:'Adjective', exFa:'در باز است.', exLatin:'Dar bâz ast.', exEn:'The door is open.'},
  {fa:'بسته', latin:'baste', en:'closed', category:'Adjective', exFa:'فروشگاه بسته است.', exLatin:'Forushgâh baste ast.', exEn:'The store is closed.'}
];
